import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = pageMetadata("/thesis", "Reproducing LeRobot Policies on SO-101 Arms — Known Robot", "Why robot-policy reproduction needs pinned software, calibration, sensor configuration, and evaluation protocols. Known Robot's scope for SO-100 and SO-101 arms.");

export default function ThesisPage() {
  return <main><SiteHeader/><article className="editorial-page">
    <header className="editorial-hero"><p className="kicker">PHASE 0 · PROJECT THESIS</p><h1>Make robot-policy transfer a testable claim.</h1><p className="editorial-deck">We help developers using low-cost, LeRobot-compatible manipulation arms determine whether a published policy can run on their hardware—and understand why when it cannot.</p><div className="thesis-meta"><span>Initial focus</span><strong>SO-100 / SO-101 manipulation</strong><span>Revision</span><strong>September 2026 · v1.0</strong></div></header>
    <section className="editorial-section"><p className="section-number">01</p><div><h2>The first community</h2><p>Our first community is practitioners actively attempting to reproduce or adapt publicly shared manipulation policies on SO-100, SO-101, and closely compatible low-cost LeRobot hardware.</p><p>It includes independent builders, robotics students, educators, open-source maintainers, small laboratories, and early robotics teams. They already share code, policies, datasets, calibration guidance, and failure reports through GitHub, Hugging Face, Discord, papers, and classrooms.</p></div></section>
    <section className="editorial-section"><p className="section-number">02</p><div><h2>The painful workflow</h2><p>A practitioner finds a promising policy, then reconstructs the conditions under which it worked: exact revision, robot configuration, calibration, cameras, observation and action conventions, dependencies, control timing, and evaluation protocol. Much of this is implicit or distributed across documentation and issue threads.</p><blockquote>“Can this policy run on my setup, and what must be true for its reported result to mean anything here?”</blockquote><p>That is the decision we intend to make faster and more defensible.</p></div></section>
    <section className="editorial-section"><p className="section-number">03</p><div><h2>Why this wedge is credible</h2><div className="criteria-grid"><div><strong>Identifiable people</strong><p>LeRobot contributors, arm owners, students, maintainers, educators, and small labs are reachable in existing technical communities.</p></div><div><strong>Observable pain</strong><p>Public reports document calibration, gripper-direction, hardware-interface, and configuration failures.</p></div><div><strong>Measurable outcome</strong><p>Time to first valid trial, successful trials, interventions, and independent reproductions can be counted.</p></div><div><strong>Existing substrate</strong><p>LeRobot supplies interfaces and dataset conventions; GitHub and Hugging Face already host the artifacts.</p></div><div><strong>No owned lab required</strong><p>Early validation can use contributor-operated hardware and local execution, with trust levels stated explicitly.</p></div><div><strong>Natural expansion</strong><p>A proven record can later cover more arms, simulations, physical agents, and accredited testing.</p></div></div></div></section>
    <section className="editorial-section"><p className="section-number">04</p><div><h2>Deliberate boundaries</h2><p>During this discovery cycle, Known Robot is not a robot manufacturer, policy marketplace, safety certifier, simulation engine, model host, or universal robotics standard.</p><p>We are studying one decision: whether a third party has enough evidence to attempt a policy transfer on low-cost manipulation hardware.</p></div></section>
    <section className="editorial-section"><p className="section-number">05</p><div><h2>Falsifiable Phase 1 hypotheses</h2><ol className="hypotheses"><li>Practitioners spend meaningful time reconstructing configuration before a valid trial.</li><li>Calibration and sensor configuration are at least as important as model metadata in transfer failures.</li><li>Success rates are frequently not comparable across repositories without additional protocol details.</li><li>Practitioners will share non-confidential failure evidence when attribution and scope are clear.</li><li>At least five qualified teams will commit an artifact, evaluation, cadence, publishable result, or introduction.</li></ol><p>We will change or abandon the wedge if 25 conversations do not support a repeated workflow with measurable cost.</p></div></section>
    <section className="decision-box"><div><p className="kicker">HELP TEST THE THESIS</p><h2>Tell us about the last policy you tried to reproduce.</h2></div><Link href="/participate">Choose how to participate →</Link></section>
  </article></main>;
}
