import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";
import { SiteHeader } from "@/components/site-header";
export const metadata: Metadata = pageMetadata("/corrections", "Corrections and disputes — Known Robot", "Correct public evidence and contributor credit through attributable, independent review.");
const repo = "https://github.com/arcofdescent1/knownrobot";
export default function CorrectionsPage() {
  return <><SiteHeader /><main className="evidence-page"><header className="editorial-hero"><p className="kicker">KEEP THE RECORD HONEST</p><h1>Corrections and disputes.</h1><p>Disagreement is evidence to examine, not a reason to erase failed outcomes or inconvenient results.</p></header>
    <section><h2>Open an inspectable request</h2><p>Include the permanent result URL, result digest, exact disputed statement, requested remedy and supporting public evidence. Credit corrections should cite the original source. Appeals must link the prior decision and explain the new evidence or procedural problem.</p><a href={`${repo}/issues/new?template=evidence-correction.yml`}>Open a correction or dispute →</a><p>Do not post private information or safety-sensitive details. For security vulnerabilities, use <a href={`${repo}/security/advisories/new`}>private security reporting</a> if enabled; otherwise contact the repository owner privately rather than publishing an exploit.</p></section>
    <section><h2>Accountable, independent triage</h2><p>Repository maintainers acknowledge the request, appoint a named reviewer independent of the submitter, policy owner and disputed decision, and disclose conflicts in the issue. They ask the contributor to respond publicly. The assigned person and current stage must be visible before the issue is treated as under review. An unanswered issue is pending, not rejected.</p><p>Aim to acknowledge within two working days and publish a triage plan within seven. These are operating targets, not a promise that volunteers have already reviewed a request. If delayed, publish the delay and next checkpoint.</p></section>
    <section><h2>Publish the decision and preserve history</h2><p>The reviewer links the exact evidence, both positions, rationale and remedy. Published evaluation evidence is immutable: corrected trial data require a new record linked to the original. Only an explicitly appointed verification reviewer can change or retract a stronger claim through the authorized review procedure. A GitHub comment alone cannot change verification.</p><p>Close the issue only after linking the implemented remedy or a substantive no-change decision. Retain the original review and disagreement. Badges follow the current attributable registry status and never award stronger status just because a dispute was opened.</p></section>
    <section><h2>Appeal without rewriting the past</h2><p>Open a linked appeal with new evidence or a specific procedural objection. A different independent reviewer evaluates it. Conflicted maintainers recuse themselves. Any reversal is a new attributable review decision, not deletion of the earlier decision. Repeated unsupported allegations may be closed with a public reason; the evidence and correction history remain inspectable.</p><a href={`${repo}/issues?q=${encodeURIComponent('"Evidence correction/dispute:" in:title')}`}>Browse requests and decisions →</a></section>
  </main></>;
}
